import type { Metadata } from 'next';
import { Montserrat, Open_Sans, Roboto } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@/components/theme-provider';


const montserrat = Montserrat({
	variable: '--font-montserrat',
	subsets: ['latin'],
});
const openSans = Open_Sans({
	variable: '--font-open-sans',
	subsets: ['latin'],
});
const roboto = Roboto({
	variable: '--font-roboto',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: "Fayokunmi's Portfolio",
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang='en'
			suppressHydrationWarning
		>
			<body
				className={`${montserrat.variable} ${openSans.variable} ${roboto.variable} antialiased`}
			>
				<ThemeProvider
					attribute='class'
					defaultTheme='system'
					enableSystem
					disableTransitionOnChange
				>
					{children}
				</ThemeProvider>
			</body>
		</html>
	);
}
